spring.application.name=ums

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/role_base
spring.datasource.username=postgres
spring.datasource.password=181035

# Jackson Configuration
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# JWT Configuration
jwt.secret=VGhpc0lzQVNlY3VyZUJhc2U2NFNlY3JldEtleUZvckpXVFRva2VuMTIzNDU2Nzg5MA==
jwt.expiration-ms=900000
jwt.refresh-secret=U2Vjb25kU2VjdXJlQmFzZTY0UmVmcmVzaEtleUZvclNwcmluZ0Jvb3QxMjM0NTY3ODkw
jwt.refresh-expiration-ms=604800000

