spring:
  # Database config
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

# Disable swagger
springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

# JWT config
jwt:
  secret: ${JWT_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}